- name: Install Docker on hosts
  hosts: staging
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker without recommends
      apt:
        name: docker.io
        state: present
        install_recommends: no
